background_mat: 
  path_top: "path_to_global_full-lenght_topologt"
  path_mat: "path_to_global_full-lenght_matrix"

domains:
  NAME_DOMAIN_1:
    path_top: "path_top_domain1"
    path_mat: "path_matrix_domain1"
    range: "domain1_ranges" e.g 10-20
  NAME_DOMAIN_2:
    path_top: "path_top_domain2"
    path_mat: "path_matrix_domain2"
    range: "domain2_ranges" e.g 40-60