background_mat: 
  path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/target_top/topol_renumered.top"
  path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/target_top/intramat_1_1_nosuflide.ndx.gz"

domains:
  G1:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G1_D/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G1_D/intramat_1_1.ndx"
    range: "49-172"
  G2:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G2/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G2/intramat_1_1.ndx"
    range: "181-289"
  G3:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G3/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G3/intramat_1_1.ndx"
    range: "293-393"
  G4:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G4_D/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G4_D/intramat_1_1.ndx"
    range: "435-558"
  G5:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G5/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G5/intramat_1_1.ndx"
    range: "539-649"
  G6:
    path_top: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G6/topol.top"
    path_mat: "/mnt/data/bruno/mego_Bruno/make_frankenstein/02_makemat_modified/G6/intramat_1_1.ndx"
    range: "658-764"
