name: cmdata 

on:
  push:
    paths:
      - 'tools/cmdata/**'
  pull_request:
    paths:
      - 'tools/cmdata/**'

jobs:
  build-linux-gromacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install generic packages
      run: |
        sudo apt-get update -qq
    - name: Build gromacs 
      run: |
        git clone --depth 1 -b release-2023 https://github.com/multi-ego/gromacs.git
        bash tools/cmdata/patch_gromacs.sh gromacs/
        cd gromacs; mkdir build; cd build
        cmake .. -DGMX_BUILD_OWN_FFTW=ON
        make  
        sudo make install
        echo 'source /usr/local/gromacs/bin/GMXRC' >> $HOME/.bashrc
        source $HOME/.bashrc
        which gmx
        

