name: cmdata 

on:
  push:
    paths:
      - 'tools/cmdata/**'
  pull_request:
    paths:
      - 'tools/cmdata/**'

env:
  CC: gcc
  CXX: g++

jobs:
  build-linux-gromacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-reset-${{ github.sha }}
        restore-keys: ccache-reset-
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Set paths
      run: |
        echo "$HOME/opt/bin" >> $GITHUB_PATH
        # path required for pytest:
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "CPATH=$HOME/opt/include:$CPATH" >> $GITHUB_ENV
        echo "INCLUDE=$HOME/opt/include:$INCLUDE" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$HOME/opt/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Install generic packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y ccache
    - name: Build gromacs 
      run: |
        git clone --depth 1 -b release-2023 https://github.com/multi-ego/gromacs.git
        bash tools/cmdata/patch_gromacs.sh gromacs/
        cd gromacs; mkdir build; mkdir exe; cd build
        ccache -s -M 100M
        cmake .. -DPREFIX=../exe/ -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        make install -j4
        ccache -s -M 100M
        source ../exe/bin/GMXRC
        which gmx
        

