name: cmdata 

on:
  push:
    paths:
      - 'tools/cmdata/**'
  pull_request:
    paths:
      - 'tools/cmdata/**'

jobs:
  build-linux-gromacs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install generic packages
      run: |
        sudo apt-get update -qq
    - name: Build gromacs 
      run: |
        git clone --depth 1 -b release-2023 https://github.com/multi-ego/gromacs.git
        cd gromacs; mkdir build; cd build
        cmake .. -DGMX_FFT_LIBRARY=fftpack -DBUILD_TESTING=OFF -DGMX_INSTALL_LEGACY_API=ON -DGMX_IMD=OFF
        make -j2 
        sudo make install
    - name: Build cmdata 
      run: |
        cd tools/cmdata; mkdir build; cd build
        cmake ../
        make
        sudo make install
        cmdata --help
    - name: Run cmdata test 
      run: |
        source /usr/local/gromacs/bin/GMXRC
        cd test; bash run_cmdata.sh; cd ..
        

