name: Test

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - --version 1.1.8
          $HOME/.local/bin/poetry config virtualenvs.in-project true
      - uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install depencies
        run: $HOME/.local/bin/poetry install -E alphafold
      - name: Run tests
        run: .venv/bin/pytest

