name: 'Multi-eGO test'

on:
  push:
    paths-ignore:
      - 'tools/cmdata/**'
  pull_request:
    paths-ignore:
      - 'tools/cmdata/**'


jobs:
  build-linux-conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install hdf5 
      run: sudo apt-get install -y libhdf5-serial-dev libhdf5-dev libhdf5
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies with conda
      run: |
        conda install --solver=classic -y python=3.12
        conda env update --solver=classic --file conda/environment.yml --name base
        conda install --solver=classic flake8
    - name: Run flake8 
      run: |
        # Flake8 exit on most issues
        # we use blake to enforce formatting 
        flake8 . --count --extend-ignore E501,W605,E731,E402,E711 --show-source --statistics
    - name: Run tests
      run: |
        $CONDA/bin/python test/run_tests.py
        cd test; bash run_make_mat.sh; cd ..

  build-linux-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: |
        python test/run_tests.py
        cd test; bash run_make_mat.sh; cd ..

  build-macos-conda:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Add conda to system path
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment:
    - name: Install dependencies with conda
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        conda install -y python=3.10
        conda env update --file conda/environment.yml --name base
    - name: Run tests
      run: |
        $CONDA/bin/python test/run_tests.py
        cd test; bash run_make_mat.sh; cd ..

  build-macos-pip:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: |
        python test/run_tests.py
        cd test; bash run_make_mat.sh; cd ..
